### PR TITLE
Updated from 9.x branch, use new measures

### PR DESCRIPTION
**Pull request by Jaff**
While scanning the sources, I discovered that some of the metrics being captured were missing; this PR attempts to update them. The file src/main/js/common/api.js illustrates this best:
```
        for (let i = 0; i < numberOfAnalyses; i++) {
          let result = {
            alert_status: "",
            bugs: "0",
            vulnerabilities: "0",
            sqale_index: "0",
            reliability_rating: "",
            security_rating: "",
            sqale_rating: ""
          };
```
In this loop, the metrics alert_status, vulnerabilities, reliability_rating, sqale_rating, and security_rating would no longer be available.

I built and installed the jar, then l ran `npm install`, then discovered upon invoking `npm start` 
```
npm start

> sonar-custom-plugin-example@7.0.0 start
> node scripts/start.js

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'react-dev-utils/prompt'
Require stack:
- /Users/mjaffe/Development/SonarQube/sonar-custom-plugin-example/scripts/start.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/mjaffe/Development/SonarQube/sonar-custom-plugin-example/scripts/start.js:34:16)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mjaffe/Development/SonarQube/sonar-custom-plugin-example/scripts/start.js'
  ]
}

Node.js v17.9.0
```

### CODE REVIEW

**Comment by jacek-poreda-sonarsource** [comment]
@dbmeneses Can you have a look at this one?

**Comment by dbmeneses** [comment]
Hi @Jaff , could you please rebase your branch on `9.x`? Github is showing changes that are already in `9.x`.

**Comment by belen-pruvost-sonarsource** [comment]
Ping @Jaff 😄  could you rebase this branch, as per Duarte's request?

**Comment by dbmeneses** [comment]
Please open a PR once it's rebased.

**Pull request closed without merging**
